using System;
using System.Collections.Generic;
using UnityEngine;

namespace PotionPop
{
    /// <summary>Metadata of a processed sprite (Resources/Art/art_index.json). Optional values have Has* flags.</summary>
    public sealed class ArtInfo
    {
        public string name;
        public int width, height;
        /// <summary>9-slice border in pixels (left, bottom, right, top).</summary>
        public Vector4 border;
        public bool hasBorder;
        /// <summary>Normalized pivot (0..1).</summary>
        public Vector2 pivot = new Vector2(0.5f, 0.5f);
        public bool hasPivot;
        /// <summary>Normalized interior rect (origin bottom-left), e.g. the label area of the world sign or of a card frame.</summary>
        public Rect inner;
        public bool hasInner;
        public float Aspect => height > 0 ? width / (float)height : 1f;
    }

    /// <summary>
    /// Sprites live flat in Resources/Art/&lt;name&gt;.png (processed by Tools/process_art.py).
    /// Metadata (inner rects, 9-slice borders, pivots) in Resources/Art/art_index.json.
    /// Missing sprites return a generated placeholder (never null) and log one warning per name.
    /// Procedural helpers generated by the pipeline: "ui_rounded" (9-slice white rounded rect), "ui_circle",
    /// "ui_soft_shadow", "ui_glow", "ui_ring", "ui_pixel", "ui_gradient_v", "ui_confetti", "ui_star_small".
    /// </summary>
    public static class Art
    {
        const string Folder = "Art/";
        const string IndexPath = "Art/art_index";
        static readonly Rect DefaultInner = new Rect(0.06f, 0.12f, 0.88f, 0.78f);

#pragma warning disable 0649 // assigned by JsonUtility
        [Serializable] class JsonSprite { public string name; public int w; public int h; public float[] border; public float[] pivot; public float[] inner; }
        [Serializable] class JsonIndex { public JsonSprite[] sprites; }
#pragma warning restore 0649

        static Dictionary<string, Sprite> _cache;          // real sprites
        static Dictionary<string, Sprite> _placeholders;   // generated stand-ins for missing names
        static HashSet<string> _missing;
        static Dictionary<string, ArtInfo> _index;
        static Texture2D _placeholderTex;
        static List<Sprite> _created;                       // sprites made with Sprite.Create (destroyed by ClearCache)

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
        static void ResetStatics()
        {
            _cache = null;
            _placeholders = null;
            _missing = null;
            _index = null;
            _placeholderTex = null;
            _created = null;
        }

        public static Sprite Get(string name)
        {
            if (string.IsNullOrEmpty(name)) name = "(empty)";
            var sprite = TryLoad(name);
            if (sprite != null) return sprite;

            // Placeholder: cached per name so repeated lookups are cheap and the warning is logged once.
            if (_placeholders == null) _placeholders = new Dictionary<string, Sprite>(StringComparer.Ordinal);
            if (_placeholders.TryGetValue(name, out var placeholder) && placeholder != null) return placeholder;
            Debug.LogWarning("[Art] Missing sprite: Resources/" + Folder + name);
            placeholder = CreatePlaceholder(name);
            _placeholders[name] = placeholder;
            return placeholder;
        }

        public static bool Exists(string name)
        {
            if (string.IsNullOrEmpty(name)) return false;
            return TryLoad(name) != null;
        }

        /// <summary>Art of a collection card ("card_&lt;id&gt;").</summary>
        public static Sprite Card(string cardId) => Get(Catalog.CardSprite(cardId));

        /// <summary>Normalized (0..1, origin bottom-left) interior rect of a framed sprite (sign label area, card window),
        /// or a generic inset when art_index.json does not list one.</summary>
        public static Rect InnerRect(string spriteName)
        {
            var info = Info(spriteName);
            return info != null && info.hasInner && info.inner.width > 0f && info.inner.height > 0f ? info.inner : DefaultInner;
        }

        /// <summary>Metadata from art_index.json, or null when the sprite is not listed.</summary>
        public static ArtInfo Info(string name)
        {
            if (string.IsNullOrEmpty(name)) return null;
            EnsureIndex();
            return _index.TryGetValue(name, out var info) ? info : null;
        }

        /// <summary>Drops cached sprites and metadata (editor tools after re-importing art).</summary>
        public static void ClearCache()
        {
            if (_placeholders != null)
                foreach (var s in _placeholders.Values) DestroyObject(s);
            if (_created != null)
                foreach (var s in _created) DestroyObject(s);
            DestroyObject(_placeholderTex);
            ResetStatics();
        }

        static void DestroyObject(UnityEngine.Object o)
        {
            if (o == null) return;
            if (Application.isPlaying) UnityEngine.Object.Destroy(o);
            else UnityEngine.Object.DestroyImmediate(o);
        }

        // ------------------------------------------------------------------ internals

        /// <summary>Real sprite or null (never a placeholder); remembers misses.</summary>
        static Sprite TryLoad(string name)
        {
            if (_cache == null) _cache = new Dictionary<string, Sprite>(256, StringComparer.Ordinal);
            if (_missing == null) _missing = new HashSet<string>(StringComparer.Ordinal);
            if (_missing.Contains(name)) return null;
            if (_cache.TryGetValue(name, out var cached))
            {
                if (cached != null) return cached;   // Unity null check: destroyed sprites are reloaded
                _cache.Remove(name);
            }

            Sprite sprite = null;
            try
            {
                sprite = Resources.Load<Sprite>(Folder + name);
                if (sprite == null)
                {
                    // Texture imported as "Default" instead of "Sprite": wrap it so the game still runs.
                    var tex = Resources.Load<Texture2D>(Folder + name);
                    if (tex != null)
                    {
                        var info = Info(name);
                        sprite = Sprite.Create(tex, new Rect(0, 0, tex.width, tex.height),
                            info != null && info.hasPivot ? info.pivot : new Vector2(0.5f, 0.5f), 100f, 0,
                            SpriteMeshType.FullRect, info != null && info.hasBorder ? info.border : Vector4.zero);
                        sprite.name = name;
                        (_created ??= new List<Sprite>()).Add(sprite);
                    }
                }
            }
            catch (Exception e)
            {
                Debug.LogWarning("[Art] Could not load " + name + ": " + e.Message);
            }

            if (sprite != null) _cache[name] = sprite;
            else _missing.Add(name);
            return sprite;
        }

        static void EnsureIndex()
        {
            if (_index != null) return;
            _index = new Dictionary<string, ArtInfo>(256, StringComparer.Ordinal);
            TextAsset asset = null;
            try { asset = Resources.Load<TextAsset>(IndexPath); }
            catch (Exception) { /* missing */ }
            if (asset == null) return;   // optional: defaults are used
            MergeIndex(asset.text);
        }

        /// <summary>
        /// Merges art_index.json content into the metadata table (tests/tools). The shipped index is loaded first, so
        /// calling this early never hides it; entries with the same name are replaced.
        /// </summary>
        public static void LoadIndexJson(string json)
        {
            EnsureIndex();
            MergeIndex(json);
        }

        static void MergeIndex(string json)
        {
            JsonIndex root;
            try { root = JsonUtility.FromJson<JsonIndex>(json); }
            catch (Exception e)
            {
                Debug.LogWarning("[Art] Could not parse art_index.json: " + e.Message);
                return;
            }
            if (root == null || root.sprites == null) return;
            foreach (var s in root.sprites)
            {
                if (s == null || string.IsNullOrEmpty(s.name)) continue;
                var info = new ArtInfo { name = s.name, width = s.w, height = s.h };
                if (s.border != null && s.border.Length >= 4)
                {
                    info.border = new Vector4(s.border[0], s.border[1], s.border[2], s.border[3]);
                    info.hasBorder = info.border != Vector4.zero;
                }
                if (s.pivot != null && s.pivot.Length >= 2)
                {
                    info.pivot = new Vector2(s.pivot[0], s.pivot[1]);
                    info.hasPivot = true;
                }
                if (s.inner != null && s.inner.Length >= 4)
                {
                    info.inner = new Rect(s.inner[0], s.inner[1], s.inner[2], s.inner[3]);
                    info.hasInner = true;
                }
                _index[s.name] = info;
            }
        }

        static Sprite CreatePlaceholder(string name)
        {
            if (_placeholderTex == null)
            {
                const int size = 64, radius = 16;
                var tex = new Texture2D(size, size, TextureFormat.RGBA32, false)
                {
                    name = "ArtPlaceholder",
                    wrapMode = TextureWrapMode.Clamp,
                    filterMode = FilterMode.Bilinear,
                    hideFlags = HideFlags.DontSave,
                };
                var pixels = new Color32[size * size];
                var fill = new Color32(255, 92, 220, 200);    // magenta tint: obviously "art missing"
                var edge = new Color32(150, 30, 130, 255);
                for (int y = 0; y < size; y++)
                for (int x = 0; x < size; x++)
                {
                    // Signed distance to a rounded rectangle → anti-aliased alpha + 2 px darker outline.
                    float dx = Mathf.Max(Mathf.Abs(x + 0.5f - size * 0.5f) - (size * 0.5f - radius), 0f);
                    float dy = Mathf.Max(Mathf.Abs(y + 0.5f - size * 0.5f) - (size * 0.5f - radius), 0f);
                    float dist = Mathf.Sqrt(dx * dx + dy * dy) - radius;   // < 0 inside
                    float alpha = Mathf.Clamp01(0.5f - dist);
                    var c = dist > -2.5f ? edge : fill;
                    c.a = (byte)(c.a * alpha);
                    pixels[y * size + x] = c;
                }
                tex.SetPixels32(pixels);
                tex.Apply(false, true);
                _placeholderTex = tex;
            }
            var b = 20f;
            var sprite = Sprite.Create(_placeholderTex, new Rect(0, 0, _placeholderTex.width, _placeholderTex.height),
                new Vector2(0.5f, 0.5f), 100f, 0, SpriteMeshType.FullRect, new Vector4(b, b, b, b));
            sprite.name = "missing:" + name;
            sprite.hideFlags = HideFlags.DontSave;
            return sprite;
        }
    }
}
