"""Manifest of every image asset in Potion Pop!.

Each entry is generated by Codex CLI (built-in image generation tool) into ArtSource/raw/<name>.png.
Run Tools/gen_art.py to (re)generate missing images, then Tools/process_art.py to turn them into sprites.

The UI kit (buttons, panels, ribbon, counters, generic icons, chests, coins, wheel, cards, fx, avatars) is shared with
Shelf Pop! — the same "Candy Boutique" design system — so those raw images were copied from that project and keep
their original prompts here (regenerating them reproduces the same style). Everything that is specific to this game
(worlds, collection cards, mascot Luna, boosters, cork, stone, logo, app icon...) is new.

The glass bottles are NOT generated here: Tools/process_art.py draws them procedurally from the same parametric
silhouette the game uses to pour the liquid (Scripts/Game/Board/BottleShape.cs), so glass and liquid always line up.

Entry fields: name, size, transparent, prompt, priority (lower runs first).
"""
from catalog import AREAS, all_cards

SQUARE = "1024x1024"
LANDSCAPE = "1536x1024"
PORTRAIT = "1024x1536"

NO_TEXT = "Absolutely no text, no letters, no numbers, no logos, no watermark, no signature."
ALPHA = "Transparent background (PNG with a real alpha channel): only the subject is opaque."

ITEM_STYLE = (
    "Premium stylized 3D render for a top-grossing cozy magical mobile puzzle game: a cute, slightly chubby, toy-like "
    "collectible item with smooth rounded shapes, rich saturated candy colors, soft studio lighting from the upper "
    "left, glossy specular highlights, a subtle warm rim light, a gentle magical glow and a few tiny sparkles, clean "
    "premium materials. Straight-on front view, centered, fully visible, filling about 85% of the image with a small "
    "empty margin. " + NO_TEXT + " No ground shadow, no floor, no background, no other objects. " + ALPHA
)

UI_STYLE = (
    "Glossy 3D casual mobile game UI element in a vibrant candy style (like a top-grossing match puzzle game): "
    "chunky soft rounded shapes, smooth plastic-like material, top-left lighting with a soft white glossy highlight, "
    "subtle bevel, clean edges, perfectly symmetric, flat straight-on front view, centered. " + NO_TEXT + " " + ALPHA
)

ICON_STYLE = (
    "Cute glossy 3D game icon from ONE consistent icon set for a candy-colored casual mobile puzzle game: chunky "
    "rounded shape, soft glossy material, top-left lighting with a small white specular highlight, a clean deep-plum "
    "outline of consistent medium thickness around the whole shape, straight-on front view, very readable at small "
    "sizes, centered and filling about 85% of the frame. No background shape, no drop shadow. " + NO_TEXT + " " + ALPHA
)

CHAR_STYLE = (
    "Premium stylized 3D character render like a Pixar or top mobile game mascot: soft subsurface fur, huge glossy "
    "sparkly eyes, rosy cheeks, appealing chubby proportions, soft studio lighting, vibrant colors. " + NO_TEXT + " " + ALPHA
)

MASCOT = (
    "Luna, the mascot of the game: an adorable chubby little witch kitten with soft lilac-gray fur, white paws and a "
    "white muzzle, huge sparkly emerald-green eyes, rosy cheeks, wearing a floppy purple witch hat decorated with "
    "tiny golden stars and a small golden crescent-moon charm, and a short purple cape with a golden star clasp"
)

ASSETS = []


def add(name, size, transparent, prompt, priority=5):
    ASSETS.append({"name": name, "size": size, "transparent": transparent, "prompt": prompt, "priority": priority})


# ================================================================================================ NEW: gameplay

add("cork", SQUARE, True,
    "A single chunky cork bottle stopper seen perfectly from the front (side view, NOT from above): a slightly "
    "tapered cylinder of warm light-brown cork with a fine porous texture, wider at the top, with a small round "
    "golden wax seal stamped with a star pressed on its front. Glossy 3D casual mobile game style, centered, filling "
    "about 80% of the frame. " + NO_TEXT + " " + ALPHA, priority=1)
add("stone_wrap", PORTRAIT, True,
    "A tall rounded capsule-shaped block of smooth pale cream limestone rock, like a stone cocoon that completely "
    "encases a potion bottle (no bottle visible): rounded top and bottom, about 2.4 times taller than wide, with a few "
    "cute cracks, small chips, tiny patches of moss and a couple of embedded glowing purple crystals. Seen straight "
    "from the front, centered, filling the image height with a small margin. Glossy stylized 3D casual mobile game "
    "style, soft top-left lighting. " + NO_TEXT + " " + ALPHA, priority=1)
add("stone_chunk", SQUARE, True,
    "A single small chunky piece of pale cream limestone rock debris with a flat chipped face, glossy stylized 3D "
    "casual game style, centered. " + NO_TEXT + " " + ALPHA, priority=3)
add("fx_bubble", SQUARE, True,
    "A single glossy soap bubble, almost transparent white with a bright white specular highlight on the upper left "
    "and a soft rainbow rim, centered, filling 80% of the frame. " + NO_TEXT + " " + ALPHA, priority=3)
add("fx_splash", SQUARE, True,
    "A cartoon liquid splash crown seen from the front: pure WHITE glossy liquid droplets bursting upward and "
    "outward in a symmetric crown shape with a few round drops flying, stylized 3D casual game style, centered. "
    "The liquid is plain white so it can be tinted. " + NO_TEXT + " " + ALPHA, priority=3)
add("bottle_rack", LANDSCAPE, True,
    "A long horizontal wooden shelf plank seen straight from the front, warm honey-oak wood with a soft rounded "
    "front edge, two small golden brackets underneath at the ends and a few tiny glowing star decorations carved on "
    "the front edge, glossy stylized 3D casual mobile game style. It fills the image width; the plank is about one "
    "eighth of the image height and centered vertically. " + NO_TEXT + " " + ALPHA, priority=2)

# ================================================================================================ NEW: boosters

BOOSTERS = [
    ("undo", "a chunky curved arrow turning back counterclockwise, glossy sky blue with a small golden sparkle"),
    ("shuffle", "two thick curved arrows (tangerine orange and bubblegum pink) crossing each other in a shuffle "
                "symbol with a few sparkles"),
    ("bottle", "a cute empty clear glass potion bottle with a cork and a round lime-green plus badge on its lower "
               "right"),
    ("crystal", "a glowing crystal ball with swirling purple and pink mist inside and a golden star sparkle, on a "
                "small golden stand"),
    ("rainbow", "a round chubby potion flask with a cork, filled with swirling rainbow-colored liquid and sparkles"),
]
for name, desc in BOOSTERS:
    add(f"booster_{name}", SQUARE, True, f"Booster power-up icon: {desc}. {ICON_STYLE}", priority=1)

add("booster_pack", SQUARE, True,
    "A gift box bundle of magic power-ups: a magic star wand, a crystal ball and a rainbow potion flask peeking out "
    "of an open purple gift box with a golden ribbon. " + ICON_STYLE, priority=3)

# ================================================================================================ NEW: icons

NEW_ICONS = [
    ("home", "a cute little round potion shop tower with a pointed purple roof, a golden star on top and a glowing "
             "round window"),
    ("profile", "a round badge with the cute face of a lilac-gray witch kitten wearing a purple witch hat with a "
                "golden star"),
    ("shop", "a cute purple shopping bag with a golden star clasp and a small pink potion bottle peeking out"),
    ("map", "a folded fantasy treasure map with a dotted trail and a red star marker"),
    ("bottle", "a cute glass potion bottle with a cork, half filled with layered pink and blue liquid"),
    ("restart", "a thick circular arrow forming a loop, glossy lime green"),
    ("pour", "a small potion bottle tilted to pour a stream of pink liquid"),
]
for name, desc in NEW_ICONS:
    add(f"icon_{name}", SQUARE, True, f"Icon: {desc}. {ICON_STYLE}", priority=2)

# ================================================================================================ NEW: mascot & avatars

for pose, desc in [
    ("wave", "standing and waving happily with one paw, holding a small glowing potion bottle in the other paw, big "
             "open-mouth smile"),
    ("cheer", "jumping with joy with both arms up, eyes happily closed, holding a small golden star, sparkles around"),
    ("sad", "sitting sadly with teary eyes and droopy ears, holding an empty potion bottle"),
    ("point", "standing and pointing to the right with one paw, winking with an encouraging smile"),
    ("sleep", "sleeping peacefully curled up on a big open spellbook, hat tilted, a small sleep bubble"),
]:
    add(f"mascot_{pose}", PORTRAIT, True, f"{MASCOT}, {desc}. Full body visible, centered. {CHAR_STYLE}", priority=2)

for animal, desc in [
    ("luna", "a lilac-gray witch kitten wearing a purple witch hat with tiny golden stars"),
    ("owl", "a fluffy baby owl wearing round glasses"),
    ("dragon", "a cute baby green dragon with tiny horns"),
    ("unicorn", "a white unicorn foal with a pastel rainbow mane and a golden horn"),
]:
    add(f"avatar_{animal}", SQUARE, True,
        f"Cute round chibi head of {desc}, facing forward, head only, centered, filling about 85% of the frame. "
        f"{CHAR_STYLE}", priority=4)

# ================================================================================================ NEW: worlds

HOME_BG = (
    "Vertical mobile game home-screen background illustration: {place}. The main building is centered in the middle "
    "of the image, a calm open ground area in the lower part, sky at the top. Premium stylized 3D render like a top "
    "casual mobile game, saturated cheerful magical colors, soft dreamy lighting, sparkles, tilt-shift miniature "
    "feeling. Keep the top 15% mostly sky and the bottom 25% calm and uncluttered because UI will be placed there. "
    + NO_TEXT + " No people, no characters. Fully opaque image, no transparency."
)
GAME_BG = (
    "Vertical mobile game background: soft-focus view of a {interior}, strongly blurred with dreamy bokeh lights and "
    "gentle magical sparkles, cozy, {tint} tones, low contrast, slightly darker in the middle so that bright glass "
    "bottles placed in the foreground read clearly, nothing in sharp focus. " + NO_TEXT + " No people. Fully opaque "
    "image, no transparency."
)
for area in AREAS:
    add(f"home_{area['id']}", PORTRAIT, False, HOME_BG.format(place=area["home"]), priority=2)
    add(f"gamebg_{area['id']}", PORTRAIT, False, GAME_BG.format(interior=area["interior"], tint=area["tint"]), priority=1)

# ================================================================================================ NEW: collection cards

for area, cid, desc, _names in all_cards():
    add(f"card_{cid}", SQUARE, True, f"A single collectible item: {desc}. {ITEM_STYLE}", priority=3)

# ================================================================================================ NEW: branding

add("logo", LANDSCAPE, True,
    "Game logo for a casual mobile game titled \"Potion Pop!\". Big chunky bubbly 3D letters reading exactly "
    "\"Potion Pop!\" (spelled P-O-T-I-O-N then P-O-P then an exclamation mark), the word Potion in white with a thick "
    "candy-purple outline and the word Pop! in glossy golden yellow with a thick orange outline, playful bouncy "
    "layout on two lines, small sparkles and a cute round potion bottle with layered pink, blue and yellow liquid "
    "and a cork next to the text, with a few bubbles. No other text. " + ALPHA, priority=1)
add("app_icon", SQUARE, False,
    f"Mobile app icon: {MASCOT}, peeking happily from behind three glass potion bottles standing in a row, each "
    "bottle filled with neat stacked layers of colored liquid (pink, blue, yellow, green), one bottle with a cork "
    "and sparkles, a vibrant candy-purple background with soft light rays and stars. Premium 3D render, square "
    f"composition, bold and readable. {NO_TEXT} Fully opaque image, no transparency.", priority=1)
add("store_sign", LANDSCAPE, True,
    "A wide empty magical wooden sign board with rounded corners and a thin golden frame, two small golden chains at "
    "the top to hang it, a little purple ribbon and two tiny golden stars on the frame corners, glossy 3D casual "
    "mobile game style, plain cream center for a label. " + UI_STYLE, priority=3)

# ================================================================================================ SHARED with Shelf Pop!
# (raw images copied from ../shelf-sorting/ArtSource/raw — same design system)

BTN = (
    "A single wide horizontal pill-shaped button (rounded rectangle with fully round ends, about 3 times wider than "
    "tall) for a casual mobile game: {color} glossy candy plastic, a thicker darker {color} bottom edge giving it a "
    "raised 3D look, a soft white glossy highlight band across the upper part, a thin darker outline. It fills the "
    "image width with a small margin. EMPTY face: no text, no icon. "
)
for color, desc in [
    ("green", "fresh lime green"), ("blue", "bright sky blue"), ("orange", "warm tangerine orange"),
    ("purple", "vivid candy purple"), ("red", "cherry red"), ("yellow", "sunny golden yellow"),
    ("pink", "bubblegum pink"), ("gray", "soft cool gray"),
]:
    add(f"btn_{color}", LANDSCAPE, True, BTN.format(color=desc) + UI_STYLE, priority=9)

add("btn_square", SQUARE, True,
    "A single rounded-square 3D button tile for a booster slot in a casual mobile game: warm cream-beige glossy "
    "plastic with a thicker darker caramel bottom edge (raised 3D look), a soft highlight on the top, a thin caramel "
    "outline, EMPTY face. Fills the image with a small margin. " + UI_STYLE, priority=9)
add("btn_round_close", SQUARE, True,
    "A round glossy cherry-red 3D close button with a bold white X symbol in the center, thick darker bottom edge, "
    "white glossy highlight, thin dark outline. " + UI_STYLE, priority=9)
add("panel_popup", SQUARE, True,
    "A large rounded-square popup window panel for a casual mobile game: a thick glossy candy-purple 3D outer frame "
    "(about 6% of the width) with a bright highlight on top and a darker purple bottom edge, and a flat warm cream "
    "inner area with a very subtle soft inner shadow along the top edge. The panel fills the whole image with a tiny "
    "margin; the inner cream area is plain and flat. " + UI_STYLE, priority=9)
add("panel_card", SQUARE, True,
    "A plain rounded-square card for a casual mobile game: flat white face with a slightly thicker light lavender-gray "
    "bottom edge giving a subtle 3D raised look, very soft rounded corners, fills the image with a tiny margin. "
    + UI_STYLE, priority=9)
add("panel_inset", LANDSCAPE, True,
    "A recessed rounded-rectangle slot (sunken into the surface) for a casual mobile game UI: soft beige color with "
    "an inner shadow along the top edge and a light highlight along the bottom edge, plain flat center. Fills the "
    "image with a small margin. " + UI_STYLE, priority=9)
add("ribbon_title", LANDSCAPE, True,
    "A wide festive title ribbon banner for a popup in a casual mobile game: glossy hot-pink ribbon with folded "
    "tails on both ends tucked behind, gentle upward curve, darker pink folds, a soft highlight, EMPTY center "
    "(no text). Fills the image width. " + UI_STYLE, priority=9)
add("pill_counter", LANDSCAPE, True,
    "A horizontal capsule counter bar (fully rounded ends, about 4 times wider than tall) for the top bar of a "
    "casual mobile game: soft cream face with a thin warm-brown outline and a subtle inner shadow, slightly glossy, "
    "EMPTY. Fills the image width with a small margin. " + UI_STYLE, priority=9)
add("progress_track", LANDSCAPE, True,
    "An empty horizontal progress bar track (capsule shape, about 6 times wider than tall): recessed deep plum-purple "
    "with an inner shadow and a thin light rim, plain. Fills the image width with a small margin. " + UI_STYLE, priority=9)
add("progress_fill", LANDSCAPE, True,
    "A horizontal progress bar fill (capsule shape, about 6 times wider than tall): glossy lime green with a bright "
    "highlight stripe along the top and slightly darker green bottom, plain. Fills the image width with a small "
    "margin. " + UI_STYLE, priority=9)

SHARED_ICONS = [
    ("heart", "a plump glossy red heart"),
    ("coin", "a shiny gold coin with an embossed star in the middle, seen from the front"),
    ("star", "a chubby glossy golden-yellow five-pointed star with rounded points"),
    ("plus", "a small round lime-green button with a bold white plus sign"),
    ("settings", "a chunky cog gear in bright periwinkle blue"),
    ("trophy", "a shiny golden trophy cup with two handles and a star on it"),
    ("collection", "a fan of three collectible cards (pink, blue and purple) with a golden star on the front card"),
    ("lock", "a chunky golden padlock with a keyhole"),
    ("play", "a round green play button with a white triangle"),
    ("pause", "a round sky-blue pause button with two white bars"),
    ("music", "a purple double music note"),
    ("sound", "a turquoise loudspeaker with sound waves"),
    ("vibration", "a coral-pink smartphone with small vibration lines on both sides"),
    ("language", "a globe with blue oceans and green continents and a little golden ring"),
    ("timer", "a red alarm clock with two bells"),
    ("skull", "a cute chubby purple skull with round eyes, friendly not scary"),
    ("check", "a bold glossy lime-green check mark"),
    ("gift", "a pink gift box with a big golden ribbon bow"),
    ("wheel", "a small colorful prize spin wheel with a golden pointer"),
    ("quest", "a clipboard with a checklist and a green check mark"),
    ("flame", "a cute glossy orange-yellow flame"),
    ("crown", "a golden crown with three round pink gems"),
    ("video", "a purple video screen with a white play triangle and a little golden sparkle"),
    ("logout", "an open orange door with a white arrow pointing out"),
    ("cloud", "a fluffy sky-blue cloud with a white up arrow"),
    ("medal_gold", "a round gold medal with a red ribbon and a star"),
    ("medal_silver", "a round silver medal with a blue ribbon and a star"),
    ("medal_bronze", "a round bronze medal with a green ribbon and a star"),
    ("arrow_back", "a chunky left-pointing arrow in sky blue"),
    ("hint", "a glowing yellow light bulb"),
    ("calendar", "a cute calendar page with a red top and a golden star"),
    ("info", "a round sky-blue badge with a white lowercase i symbol"),
    ("share", "a green round badge with three connected dots share symbol"),
]
for name, desc in SHARED_ICONS:
    add(f"icon_{name}", SQUARE, True, f"Icon: {desc}. {ICON_STYLE}", priority=9)

add("booster_wand", SQUARE, True,
    "Booster power-up icon: a magic wand with a big glowing golden star on top, pink-and-white striped stick and "
    "sparkles. " + ICON_STYLE, priority=9)

for animal, desc in [
    ("puppy", "a golden puppy with floppy ears"), ("kitten", "a gray tabby kitten"), ("bunny", "a white bunny with pink ears"),
    ("duck", "a yellow duckling"), ("panda", "a baby panda"), ("fox", "an orange fox cub"),
    ("bear", "a brown bear cub"), ("frog", "a green frog"),
]:
    add(f"avatar_{animal}", SQUARE, True,
        f"Cute round chibi head of {desc}, facing forward, head only, centered, filling about 85% of the frame. "
        f"{CHAR_STYLE}", priority=9)

add("chest_closed", SQUARE, True,
    "A treasure chest in royal blue with shiny gold trims, rivets and a golden star emblem on the front, closed. "
    + ICON_STYLE, priority=9)
add("chest_open", SQUARE, True,
    "The same royal blue treasure chest with gold trims and a golden star emblem, lid open, warm golden light and "
    "gold coins and stars bursting out. " + ICON_STYLE, priority=9)
add("coins_small", SQUARE, True, "A small stack of three shiny gold star coins. " + ICON_STYLE, priority=9)
add("coins_medium", SQUARE, True, "A pile of shiny gold star coins. " + ICON_STYLE, priority=9)
add("coins_large", SQUARE, True, "A big overflowing sack of shiny gold star coins. " + ICON_STYLE, priority=9)
add("hearts_refill", SQUARE, True, "Three plump glossy red hearts grouped together with sparkles. " + ICON_STYLE, priority=9)
add("spin_wheel", SQUARE, True,
    "A lucky prize wheel seen perfectly straight on: a perfect circle divided into EXACTLY EIGHT (8) equal pie "
    "segments of 45 degrees each, with one segment border pointing straight up; going clockwise from the top the "
    "segment colors are pink, yellow, mint, sky blue, purple, orange, red, lime green, a glossy gold rim with small white light "
    "bulbs, a golden center hub, EMPTY segments (no icons). Fills the frame. " + UI_STYLE, priority=9)
add("spin_pointer", PORTRAIT, True,
    "A glossy golden prize-wheel pointer pin shaped like a teardrop pointing straight DOWN, with a red gem in the "
    "round top. " + UI_STYLE, priority=9)
add("card_back", PORTRAIT, True,
    "The back of a collectible trading card: rounded rectangle, glossy royal purple with a pattern of small golden "
    "stars and a big golden star medallion in the center, golden border. Fills the image. " + UI_STYLE, priority=9)
add("card_frame", PORTRAIT, True,
    "An empty collectible card frame: rounded rectangle with a glossy golden ornamental border and a plain white "
    "rounded inner area (empty), a small golden star at the top center of the border. Fills the image. "
    + UI_STYLE, priority=9)
add("sunburst", SQUARE, True,
    "Soft radiating golden-yellow light rays (sunburst) from the center fading out to transparent at the edges, "
    "glowing, magical. " + ALPHA + " " + NO_TEXT, priority=9)
add("fx_sparkle", SQUARE, True,
    "A single glowing four-pointed sparkle star, bright white core with a soft yellow glow, centered. " + ALPHA
    + " " + NO_TEXT, priority=9)
add("fx_poof", SQUARE, True,
    "A cute cartoon puff of white smoke (cloud poof) with soft round bubbles, glossy 3D casual style, centered. "
    + ALPHA + " " + NO_TEXT, priority=9)
add("hand_pointer", SQUARE, True,
    "A cute cartoon tutorial hand: a chubby white-gloved cartoon hand with the index finger pointing UP-LEFT (as if "
    "tapping something above it), purple cuff at the wrist, glossy 3D casual mobile game style, centered. "
    + NO_TEXT + " " + ALPHA, priority=9)

SHARED = {
    a["name"] for a in ASSETS if a["priority"] == 9
}
